# Conda environment for building the MELODIES-MONET docs
name: melodies-monet-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  #
  # melodies_monet deps
  - matplotlib-base
  - monet
  - monetio
  - netcdf4
  - numpy
  - pandas=2
  - pillow
  #
  # Extras
  - numba
  - pooch
  - timezonefinder
  - typer<0.26
  - wrf-python  # for WRF-Chem reader in monetio
  #
  # Docs
  - ipykernel
  - jupyterlab=4.*
  - jupytext
  - myst-nb>=0.14
  - nbclient
  - sphinx=7.*
  - sphinx-autobuild
  - sphinx-click
  - sphinx-design
  - sphinx_rtd_theme
  - sphinx-togglebutton
  #
  - pip
  - pip:
    # melodies_monet itself
    - '-e ../'
